using System.Collections.Generic;

namespace Connector.Presentation.Resources1
{
    public class Cities
    {
        #region Romanian Cities

        public Dictionary<int, string> Dict = new Dictionary<int, string>
        {
            { 1, "Abrud" },
            { 2, "Adjud" },
            { 3, "Agnita" },
            { 4, "Aiud" },
            { 5, "Alba Iulia" },
            { 6, "Aleșd" },
            { 7, "Alexandria" },
            { 8, "Amara" },
            { 9, "Anina" },
            { 10, "Aninoasa" },
            { 11, "Arad" },
            { 12, "Ardud" },
            { 13, "Avrig" },
            { 14, "Azuga" },
            { 15, "Babadag" },
            { 16, "Băbeni" },
            { 17, "Bacău" },
            { 18, "Baia de Aramă" },
            { 19, "Baia de Arieș" },
            { 20, "Baia Mare" },
            { 21, "Baia Sprie" },
            { 22, "Băicoi" },
            { 23, "Băile Govora" },
            { 24, "Băile Herculane" },
            { 25, "Băile Olănești" },
            { 26, "Băile Tușnad" },
            { 27, "Băilești" },
            { 28, "Bălan" },
            { 29, "Bălcești" },
            { 30, "Balș" },
            { 31, "Băneasa" },
            { 32, "Baraolt" },
            { 33, "Bârlad" },
            { 34, "Bechet" },
            { 35, "Beclean" },
            { 36, "Beiuș" },
            { 37, "Berbești" },
            { 38, "Berești" },
            { 39, "Bicaz" },
            { 40, "Bistrița" },
            { 41, "Blaj" },
            { 42, "Bocșa" },
            { 43, "Boldești-Scăeni" },
            { 44, "Bolintin-Vale" },
            { 45, "Borșa" },
            { 46, "Borsec" },
            { 47, "Botoșani" },
            { 48, "Brad" },
            { 49, "Bragadiru" },
            { 50, "Brăila" },
            { 51, "Brașov" },
            { 52, "Breaza" },
            { 53, "Brezoi" },
            { 54, "Broșteni" },
            { 55, "Bucecea" },
            { 56, "București" },
            { 57, "Budești" },
            { 58, "Buftea" },
            { 59, "Buhuși" },
            { 60, "Bumbești-Jiu" },
            { 61, "Bușteni" },
            { 62, "Buzău" },
            { 63, "Buziaș" },
            { 64, "Cajvana" },
            { 65, "Calafat" },
            { 66, "Călan" },
            { 67, "Călărași" },
            { 68, "Călimănești" },
            { 69, "Câmpeni" },
            { 70, "Câmpia Turzii" },
            { 71, "Câmpina" },
            { 72, "Câmpulung Moldovenesc" },
            { 73, "Câmpulung" },
            { 74, "Caracal" },
            { 75, "Caransebeș" },
            { 76, "Carei" },
            { 77, "Cavnic" },
            { 78, "Căzănești" },
            { 79, "Cehu Silvaniei" },
            { 80, "Cernavodă" },
            { 81, "Chișineu-Criș" },
            { 82, "Chitila" },
            { 83, "Ciacova" },
            { 84, "Cisnădie" },
            { 85, "Cluj-Napoca" },
            { 86, "Codlea" },
            { 87, "Comănești" },
            { 88, "Comarnic" },
            { 89, "Constanța" },
            { 90, "Copșa Mică" },
            { 91, "Corabia" },
            { 92, "Costești" },
            { 93, "Covasna" },
            { 94, "Craiova" },
            { 95, "Cristuru Secuiesc" },
            { 96, "Cugir" },
            { 97, "Curtea de Argeș" },
            { 98, "Curtici" },
            { 99, "Dăbuleni" },
            { 100, "Darabani" },
            { 101, "Dărmănești" },
            { 102, "Dej" },
            { 103, "Deta" },
            { 104, "Deva" },
            { 105, "Dolhasca" },
            { 106, "Dorohoi" },
            { 107, "Drăgănești-Olt" },
            { 108, "Drăgășani" },
            { 109, "Dragomirești" },
            { 110, "Drobeta-Turnu Severin" },
            { 111, "Dumbrăveni" },
            { 112, "Eforie" },
            { 113, "Făgăraș" },
            { 114, "Făget" },
            { 115, "Fălticeni" },
            { 116, "Făurei" },
            { 117, "Fetești" },
            { 118, "Fieni" },
            { 119, "Fierbinți-Târg" },
            { 120, "Filiași" },
            { 121, "Flămânzi" },
            { 122, "Focșani" },
            { 123, "Frasin" },
            { 124, "Fundulea" },
            { 125, "Găești" },
            { 126, "Galați" },
            { 127, "Gătaia" },
            { 128, "Geoagiu" },
            { 129, "Gheorgheni" },
            { 130, "Gherla" },
            { 131, "Ghimbav" },
            { 132, "Giurgiu" },
            { 133, "Gura Humorului" },
            { 134, "Hârlău" },
            { 135, "Hârșova" },
            { 136, "Hațeg" },
            { 137, "Horezu" },
            { 138, "Huedin" },
            { 139, "Hunedoara" },
            { 140, "Huși" },
            { 141, "Ianca" },
            { 142, "Iași" },
            { 143, "Iernut" },
            { 144, "Ineu" },
            { 145, "Însurăței" },
            { 146, "Întorsura Buzăului" },
            { 147, "Isaccea" },
            { 148, "Jibou" },
            { 149, "Jimbolia" },
            { 150, "Lehliu Gară" },
            { 151, "Lipova" },
            { 152, "Liteni" },
            { 153, "Livada" },
            { 154, "Luduș" },
            { 155, "Lugoj" },
            { 156, "Lupeni" },
            { 157, "Măcin" },
            { 158, "Măgurele" },
            { 159, "Mangalia" },
            { 160, "Mărășești" },
            { 161, "Marghita" },
            { 162, "Medgidia" },
            { 163, "Mediaș" },
            { 164, "Miercurea Ciuc" },
            { 165, "Miercurea Nirajului" },
            { 166, "Miercurea Sibiului" },
            { 167, "Mihăilești" },
            { 168, "Milișăuți" },
            { 169, "Mioveni" },
            { 170, "Mizil" },
            { 171, "Moinești" },
            { 172, "Moldova Nouă" },
            { 173, "Moreni" },
            { 174, "Motru" },
            { 175, "Murfatlar" },
            { 176, "Murgeni" },
            { 177, "Nădlac" },
            { 178, "Năsăud" },
            { 179, "Năvodari" },
            { 180, "Negrești" },
            { 181, "Negrești-Oaș" },
            { 182, "Negru Vodă" },
            { 183, "Nehoiu" },
            { 184, "Novaci" },
            { 185, "Nucet" },
            { 186, "Ocna Mureș" },
            { 187, "Ocna Sibiului" },
            { 188, "Ocnele Mari" },
            { 189, "Odobești" },
            { 190, "Odorheiu Secuiesc" },
            { 191, "Oltenița" },
            { 192, "Onești" },
            { 193, "Oradea" },
            { 194, "Orăștie" },
            { 195, "Oravița" },
            { 196, "Orșova" },
            { 197, "Oțelu Roșu" },
            { 198, "Otopeni" },
            { 199, "Ovidiu" },
            { 200, "Panciu" },
            { 201, "Pâncota" },
            { 202, "Pantelimon" },
            { 203, "Pașcani" },
            { 204, "Pătârlagele" },
            { 205, "Pecica" },
            { 206, "Petrila" },
            { 207, "Petroșani" },
            { 208, "Piatra Neamț" },
            { 209, "Piatra-Olt" },
            { 210, "Pitești" },
            { 211, "Ploiești" },
            { 212, "Plopeni" },
            { 213, "Podu Iloaiei" },
            { 214, "Pogoanele" },
            { 215, "Popești-Leordeni" },
            { 216, "Potcoava" },
            { 217, "Predeal" },
            { 218, "Pucioasa" },
            { 219, "Răcari" },
            { 220, "Rădăuți" },
            { 221, "Râmnicu Sărat" },
            { 222, "Râmnicu Vâlcea" },
            { 223, "Râșnov" },
            { 224, "Recaș" },
            { 225, "Reghin" },
            { 226, "Reșița" },
            { 227, "Roman" },
            { 228, "Roșiorii de Vede" },
            { 229, "Rovinari" },
            { 230, "Roznov" },
            { 231, "Rupea" },
            { 232, "Săcele" },
            { 233, "Săcueni" },
            { 234, "Salcea" },
            { 235, "Săliște" },
            { 236, "Săliștea de Sus" },
            { 237, "Salonta" },
            { 238, "Sângeorgiu de Pădure" },
            { 239, "Sângeorz-Băi" },
            { 240, "Sânnicolau Mare" },
            { 241, "Sântana" },
            { 242, "Sărmașu" },
            { 243, "Satu Mare" },
            { 244, "Săveni" },
            { 245, "Scornicești" },
            { 246, "Sebeș" },
            { 247, "Sebiș" },
            { 248, "Segarcea" },
            { 249, "Seini" },
            { 250, "Sfântu Gheorghe" },
            { 251, "Sibiu" },
            { 252, "Sighetu Marmației" },
            { 253, "Sighișoara" },
            { 254, "Simeria" },
            { 255, "Șimleu Silvaniei" },
            { 256, "Sinaia" },
            { 257, "Siret" },
            { 258, "Slănic" },
            { 259, "Slănic-Moldova" },
            { 260, "Slatina" },
            { 261, "Slobozia" },
            { 262, "Solca" },
            { 263, "Șomcuta Mare" },
            { 264, "Sovata" },
            { 265, "Ștefănești, Argeș" },
            { 266, "Ștefănești, Botoșani" },
            { 267, "Ștei" },
            { 268, "Strehaia" },
            { 269, "Suceava" },
            { 270, "Sulina" },
            { 271, "Tălmaciu" },
            { 272, "Țăndărei" },
            { 273, "Târgoviște" },
            { 274, "Târgu Bujor" },
            { 275, "Târgu Cărbunești" },
            { 276, "Târgu Frumos" },
            { 277, "Târgu Jiu" },
            { 278, "Târgu Lăpuș" },
            { 279, "Târgu Mureș" },
            { 280, "Târgu Neamț" },
            { 281, "Târgu Ocna" },
            { 282, "Târgu Secuiesc" },
            { 283, "Târnăveni" },
            { 284, "Tășnad" },
            { 285, "Tăuții-Măgherăuș" },
            { 286, "Techirghiol" },
            { 287, "Tecuci" },
            { 288, "Teiuș" },
            { 289, "Țicleni" },
            { 290, "Timișoara" },
            { 291, "Tismana" },
            { 292, "Titu" },
            { 293, "Toplița" },
            { 294, "Topoloveni" },
            { 295, "Tulcea" },
            { 296, "Turceni" },
            { 297, "Turda" },
            { 298, "Turnu Măgurele" },
            { 299, "Ulmeni" },
            { 300, "Ungheni" },
            { 301, "Uricani" },
            { 302, "Urlați" },
            { 303, "Urziceni" },
            { 304, "Valea lui Mihai" },
            { 305, "Vălenii de Munte" },
            { 306, "Vânju Mare" },
            { 307, "Vașcău" },
            { 308, "Vaslui" },
            { 309, "Vatra Dornei" },
            { 310, "Vicovu de Sus" },
            { 311, "Victoria" },
            { 312, "Videle" },
            { 313, "Vișeu de Sus" },
            { 314, "Vlăhița" },
            { 315, "Voluntari" },
            { 316, "Vulcan" },
            { 317, "Zalău" },
            { 318, "Zărnești" },
            { 319, "Zimnicea" },
            { 320, "Zlatna" }
        };

        #endregion
    }
}